services:
  - type: web
    name: fitness-buddy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: IBM_API_KEY
        value: 4ItIatS7TkhaExLAzYfCcyxu_fQmk8H83cynzwuIdOGs
      - key: IBM_PROJECT_ID
        value: 942ca098-2478-4985-a928-02368453f9a4
      - key: IBM_MODEL_ID
        value: ibm/granite-4-h-small
      - key: IBM_API_URL
        value: https://us-south.ml.cloud.ibm.com/ml/v1/text/chat?version=2023-05-29
      - key: IBM_IAM_URL
        value: https://iam.cloud.ibm.com/identity/token
